version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    env_file: ./.env
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    image: book-store
    build: .
    env_file: ./.env
    ports:
      - "8088:8080"
      - "5005:5005"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimeZone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT"
